name: Build and deploy Node.js app to ECSsdc

on:
  push:
    branches:
      - pipeline-implementation
    paths:
      - 'apps/user/**'
  workflow_dispatch:

env:
  ECR_IMAGE_TAG: "USER_v_${{ github.run_number }}"
  ECR_REPOSITORY: "dev-services"
  AWS_REGION: "ap-southeast-1"
  CLUSTER: "DEV-NGOTAG-CLUSTER"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: ap-southeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: dev-services
          IMAGE_TAG: "USER_v_${{ github.run_number }}"
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f Dockerfiles/Dockerfile.user .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker image list
          
      - name: Set environment variables
        run: |
          echo "ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}" >> $GITHUB_ENV
          echo "ECR_REPOSITORY=dev-services" >> $GITHUB_ENV
          echo "IMAGE_TAG=USER_v_${{ github.run_number }}" >> $GITHUB_ENV
   
      - name: Print environment variables
        run: |
          echo "ECR_REGISTRY: $ECR_REGISTRY"
          echo "ECR_REPOSITORY: $ECR_REPOSITORY"
          echo "IMAGE_TAG: $IMAGE_TAG"
     
      - name: Retrieve Repository URI
        run: |
          REPOSITORY_URI=$(aws ecr describe-repositories --repository-names ${{ env.ECR_REPOSITORY }} --region ${{ env.AWS_REGION }} | jq -r '.repositories[].repositoryUri')
          echo "REPOSITORY_URI=${REPOSITORY_URI}" >> $GITHUB_ENV
      
      - name: Replace executionRoleArn in task definition
        run: |
          sed -i "s#\"executionRoleArn\": \"arn:aws:iam::.*:role/ecsTaskExecutionRole\"#\"executionRoleArn\": \"arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/ecsTaskExecutionRole\"#" taskdef/user-service.json

      